/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void studentMode(GButton source, GEvent event) { //_CODE_:studentButtin:712179:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  board.isDrawing = true;
} //_CODE_:studentButtin:712179:

public void teacherMode(GButton source, GEvent event) { //_CODE_:teacherButton:875382:
  println("button2 - GButton >> GEvent." + event + " @ " + millis());
  board.isDrawing = true;
} //_CODE_:teacherButton:875382:

public void instructionButtonPressed(GButton source, GEvent event) { //_CODE_:instructionButton:227920:
  println("instructionButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:instructionButton:227920:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  studentButtin = new GButton(this, 206, 274, 100, 30);
  studentButtin.setText("Student");
  studentButtin.addEventHandler(this, "studentMode");
  teacherButton = new GButton(this, 206, 342, 100, 30);
  teacherButton.setText("Teacher");
  teacherButton.addEventHandler(this, "teacherMode");
  instructionButton = new GButton(this, 460, 470, 40, 30);
  instructionButton.setText("?");
  instructionButton.addEventHandler(this, "instructionButtonPressed");
}

// Variable declarations 
// autogenerated do not edit
GButton studentButtin; 
GButton teacherButton; 
GButton instructionButton; 
